# Site settings
title: Sophia Aumüller-Wagner 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Website of Sophia Aumüller-Wagner, Diversity Consultant, Project Manager, Workshop Instructor, Sociologist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
